"""s2_4_chunk_status —— 已发布切片的启用/禁用软标志(DB-DESIGN §3)。

下线不能物理删:切片可能已被 `message_citations.ref_id` 引用过,删了历史会话的引用悬空。
配套两件事在代码侧:两条召回 SQL 都过滤 `status='active'`;禁用时一并清空 `embedding`。

Revision ID: 080047c67e96
Revises: s3a1b2c3d4e5
Create Date: 2026-08-25 20:38:36.318438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080047c67e96'
down_revision: Union[str, Sequence[str], None] = 's3a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('status', sa.Text(), server_default='active', nullable=False))
    op.create_check_constraint('ck_chunks_status', 'chunks', "status IN ('active', 'disabled')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_chunks_status', 'chunks', type_='check')
    op.drop_column('chunks', 'status')
    # ### end Alembic commands ###
