"""s2_4_partial_unique_active_chunk_seq —— (doc_id, seq) 只约束在用的行。

退休行(被引用过、被文档新一版取代)保留原来的 `seq`,与新一代的同号行共存。
原先靠"把退休行的 seq 挪进负号区"来让开全表唯一约束,那套编码**跨代不唯一** ——
同一个 seq 退休两次会撞同一个负号槽(2026-08-25 实测炸在这里)。
现在把意图直接写进约束:一份文档同一时刻只能有一条 `status='active'` 的 seq=N。

Revision ID: f1c8fb31883d
Revises: 080047c67e96
Create Date: 2026-08-25 21:03:23.985348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c8fb31883d'
down_revision: Union[str, Sequence[str], None] = '080047c67e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_chunks_doc_seq'), 'chunks', type_='unique')
    # 旧编码留下的负号行:还原 seq,并改用 meta 旗标表达"这是退休行"
    op.execute(
        """
        UPDATE chunks
        SET seq = -seq - 1,
            meta = meta || '{"retired": true}'::jsonb
        WHERE seq < 0
        """
    )
    op.create_index('uq_chunks_doc_seq_active', 'chunks', ['doc_id', 'seq'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_chunks_doc_seq_active', table_name='chunks', postgresql_where=sa.text("status = 'active'"))
    op.create_unique_constraint(op.f('uq_chunks_doc_seq'), 'chunks', ['doc_id', 'seq'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
